---

- hosts: local
  roles:
    - { role: packages }
    - { role: configs }
    - { role: emacs }
    - { role: keybindings }
    - { role: angstwad.docker_ubuntu, docker_group_members: [azx], become: yes }
    - { role: services }
    - { role: backups }
