- name: Create symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: '{{ playbook_dir }}/services/files/syncthing', dest: '/etc/systemd/user/syncthing@.service' }

- name: enable synthing
  systemd:
    name: syncthing@azx.service
    state: started
    enabled: yes
