- name: Create symlinks
  become_user: azx
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: '{{ playbook_dir }}/keybindings/files/keymap.xkb', dest: '~/.keymap.xkb' }


- name: Set keybindings
  become_user: azx
  shell: |
    xkbcomp -I$HOME/.xkb $HOME/.keymap.xkb $DISPLAY
