# - name: Create xkb config dir
#   file:
#     path: "{{ item.dest }}"
#     state: directory
#     mode: '0755'
#   with_items:
#     - { dest: '~/.config/xkb/compat' }
#     - { dest: '~/.config/xkb/types' }
#     - { dest: '~/.config/xkb/symbols' }

# - name: Create symlinks
#   file:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     state: link
#   with_items:
#     - { src: '{{ playbook_dir }}/create_symlinks/files/xkb/symbols', dest: '~/.config/xkb/symbols/custom' }
#     - { src: '{{ playbook_dir }}/create_symlinks/files/xkb/types', dest: '~/.config/xkb/types/custom' }
#     - { src: '{{ playbook_dir }}/create_symlinks/files/xkb/compat', dest: '~/.config/xkb/compat/custom' }


# - name: Set keybindings
#   shell: |
#     # setxkbmap -compat custom -print | xkbcomp -I"$HOME/.config/xkb" - "${DISPLAY%%.*}"
#     # setxkbmap -types custom -print | xkbcomp -I"$HOME/.config/xkb" - "${DISPLAY%%.*}"
#     setxkbmap -symbols custom -print | xkbcomp -I"$HOME/.config/xkb" - "${DISPLAY%%.*}"

# xkbcomp create_symlinks/files/keymap.xkb $DISPLAY
# xkbcomp -I$HOME/.xkb $HOME/.keymap.xkb $DISPLAY
# setxkbmap -print
# setxkbmap -symbols custom -print | xkbcomp -I"$HOME/.config/xkb" - "${DISPLAY%%.*}"



# xkb_keymap {
#         xkb_keycodes  { include "evdev+aliases(qwerty)" };
#         xkb_types     { include "complete"      };
#         xkb_compat    { include "complete"      };
#         xkb_symbols   { include "pc+us+ru:2+inet(evdev)+ctrl(nocaps)"   };
#         xkb_geometry  { include "pc(pc105)"     };
# };


 # xkb_symbols "custom_kb" {
 #    include "ctrl(nocaps)"
 #     include "ctrl(swapcaps)"

 #     key <ESC> { [Control_L] }
#  };


#  xkb_symbols "arrows" {
#     key <LEFT> { [ h ] };
#     key <DOWN> { [ j ] };
#     key <UP>   { [ k ] };
#     key <RGHT> { [ l ] };
#     modifier_map Lock { <LCTL> };
# }

# partial modifier_keys
# xkb_symbols "swapcaps" {
 #    replace key <CAPS> { [ Control_L ] };
 #    replace key <LCTL> { [ Caps_Lock ] };
 #    modifier_map Control { <CAPS> };
 #    modifier_map  Lock { <LCTL> };
# };

