- name: Create emacs config dir
  file:
    path: '~/.emacs.d'
    state: directory
    mode: '0755'

- name: Clone emacs doom configs
  git:
    repo: 'https://github.com/hlissner/doom-emacs'
    dest: '~/.emacs.d'

- name: Create doom config dir
  file:
    path: '~/.doom.d'
    state: directory
    mode: '0755'

- name: Create symlinks for custom doom configs
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: '{{ playbook_dir }}/emacs/files/init.el', dest: '~/.doom.d/init.el' }
    - { src: '{{ playbook_dir }}/emacs/files/config.el', dest: '~/.doom.d/config.el' }
    - { src: '{{ playbook_dir }}/emacs/files/packages.el', dest: '~/.doom.d/packages.el' }

- name: Refresh doom
  shell: |
    ~/.emacs.d/bin/doom refresh
