- name: Create symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: '{{ playbook_dir }}/setup_configs/files/bash_profile', dest: '~/.bash_profile' }
    - { src: '{{ playbook_dir }}/setup_configs/files/karabiner.json', dest: '~/.config/karabiner/karabiner.json' }
    - { src: '{{ playbook_dir }}/setup_configs/files/nvim', dest: '~/.config/nvim/init.vim' }
